name: Apply DB schema migrations

# 👉 Only run this workflow when a change is made to the main branch
on:
  push:

jobs:
  apply_migrations:
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies & tooling
        run: |
          npm install --legacy-peer-deps
          npm install -g drizzle-orm drizzle-kit pg
      - name: Apply migrations
        run: drizzle-kit migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}