name: Deploy Preview

on: [pull_request]

jobs:
    deploy-preview:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - uses: actions/setup-node@v4
          with:
            node-version: 18
            cache: "pnpm"
        - run: pnpm install
        - name: Get git branch name
          id: branch-name
          uses: tj-actions/branch-names@v8