name: playwright tests
on:
  workflow_run:
    workflows: [Preview Deployment]
    types:
      - completed

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"
    - name: Install testing browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30